version: "3.8"

services:
  mtv_dl_web:
    build: .
    container_name: mtv_dl_web
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./downloads:/downloads
      - ./config:/config
      - ./.mtv_dl_web:/home/appuser/.mtv_dl_web
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped
